### PR TITLE
updated to v1.0

### PR DESCRIPTION
**Pull request by jonathanBieler**
Hi @rened, I've updated this to v1.0. I've tried some alternatives like `Weave.jl` but I actually prefer this package.  There's maybe some issue with dependencies on travis, let's see how the tests goes.

### CODE REVIEW

**Comment by rened** [comment]
great, thank you very much!

**Comment by jonathanBieler** [comment]
Can we merge this ? If you want, you can also give me access so I can help you with maintaining the package.

**Comment by rened** [comment]
thanks & sorry for the slow response time!

**Comment by jonathanBieler** [comment]
Thanks, no problems.

**Pull request merged**
